ZSHRC_DIR="$HOME/.config/shell-config/zshrc"

source "$ZSHRC_DIR/history.zsh"
source "$ZSHRC_DIR/zsh-completions.zsh"
source "$ZSHRC_DIR/fzf.zsh"
source "$ZSHRC_DIR/zoxide.zsh"
source "$ZSHRC_DIR/yazi.zsh"
source "$ZSHRC_DIR/eza.zsh"
source "$ZSHRC_DIR/bat.zsh"
source "$ZSHRC_DIR/aliases.zsh"
source "$ZSHRC_DIR/zsh-autosuggestions.zsh"
source "$ZSHRC_DIR/starship.zsh"
source "$ZSHRC_DIR/zsh-syntax-highlighting.zsh"
